using Npgsql;
using SupportCenter.Classes;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace SupportCenter
{
    /// <summary>
    /// Логика взаимодействия для AppealForm.xaml
    /// </summary>
    public partial class AppealForm : Window
    {
        public AppealForm()
        {
            InitializeComponent();
        }

        private void cancelButton_Click(object sender, RoutedEventArgs e)
        {
            MainWindow mainWindow = new MainWindow();
            mainWindow.Show();  
            this.Close();
        }

        private void buttonProgram_Click(object sender, RoutedEventArgs e)
        {
            workAreaControl.SelectedIndex = 0;
        }

        private void buttonFolder_Click(object sender, RoutedEventArgs e)
        {
            workAreaControl.SelectedIndex = 1;
        }
        public void loadAppealProgram()
        {

            dbConnect db_connect = new dbConnect();
            DataTable table = new DataTable();
            NpgsqlCommand command = new NpgsqlCommand(
                        "SELECT u.id_appeal_program, " +
                        "p.name_program, " +
                        "u.pc_name, " +
                        "u.ip_pc, " +
                        "user_applicant.user_name AS applicant_user," +
                        "oib_user.user_name AS oib_user_name, " +
                        "u.oib_status_responsible, " +
                        "oit_user.user_name AS oit_user_name, " +
                        "u.oit_status_responsible, " +
                        "otp_user.user_name AS otp_user_name, " +
                        "u.otp_status_executor " +
                        "FROM main.appealprogram u " +
                        "LEFT JOIN main.users oib_user ON u.oib_responsible = oib_user.user_id " +
                        "LEFT JOIN main.users oit_user ON u.oit_responsible = oit_user.user_id " +
                        "LEFT JOIN main.users otp_user ON u.otp_executor = otp_user.user_id " +
                        "LEFT JOIN main.users user_applicant ON u.applicant = user_applicant.user_id " +
                        "LEFT JOIN main.program p ON u.id_program = p.id_program", db_connect.GetConnection());
            db_connect.openConnection();
            command.ExecuteNonQuery();
            NpgsqlDataAdapter adapter = new NpgsqlDataAdapter(command);
            NpgsqlDataReader reader = command.ExecuteReader();
            List<appealProgram> result = new List<appealProgram>();

            while (reader.Read())
            {
                string oibStatus = null;
                string oitStatus = null;
                string otpStatus = null;
                string otpExecutor = null;

               
                switch (Convert.ToString(reader[6]))
                {
                    case "0": oibStatus = "Не согласовано"; break;
                    case "1": oibStatus = "Согласовано"; break;
                    case "2": oibStatus = "Отказано"; break;

                }
                switch (Convert.ToString(reader[8]))
                {
                    case "0": oitStatus = "Не согласовано"; break;
                    case "1": oitStatus = "Согласовано"; break;
                    case "2": oitStatus = "Отказано"; break;

                }
               
                if (Convert.ToString(reader[10]) == "0")
                {
                    otpStatus = "Не в работе";
                }
                
                if (Convert.ToString(reader[9]) == "")
                {
                    otpExecutor = "Нет исполнителя";
                }
                else otpExecutor = Convert.ToString(reader[9]);



                    result.Add(new appealProgram(Convert.ToInt32(reader[0]), Convert.ToString(reader[1]), Convert.ToString(reader[2]), Convert.ToString(reader[3]), Convert.ToString(reader[4]),
                        Convert.ToString(reader[5]), oibStatus, Convert.ToString(reader[7]), oitStatus, otpExecutor, otpStatus));

            }
            reader.Close();
            appealProgramDataGrid.ItemsSource = result;

           

        }

        private void appealProgramCreate_Click(object sender, RoutedEventArgs e)
        {
            CreateAppealProgramForm createAppealProgramForm = new CreateAppealProgramForm();
            createAppealProgramForm.ShowDialog();
        }

        private void appealProgramShow_Click(object sender, RoutedEventArgs e)
        {
            loadAppealProgram();
        }

        private void appealProgramDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            appealProgramDataGrid.Columns[0].Header = "ID";
            appealProgramDataGrid.Columns[1].Header = "ПРОГРАММА";
            appealProgramDataGrid.Columns[2].Header = "КОМПЬЮТЕР";
            appealProgramDataGrid.Columns[3].Header = "IP АДРЕС";
            appealProgramDataGrid.Columns[4].Header = "ИЦИЦИАТОР";
            appealProgramDataGrid.Columns[5].Header = "СОГЛАСУБЮЩИЙ ОИБ";
            appealProgramDataGrid.Columns[6].Header = "СТАТУС";
            appealProgramDataGrid.Columns[7].Header = "СОГЛАСУЮЩИЙ ОИТ";
            appealProgramDataGrid.Columns[8].Header = "СТАТУС";
            appealProgramDataGrid.Columns[9].Header = "ИСПОЛНИТЕЛЬ ОТП";
            appealProgramDataGrid.Columns[10].Header = "ЭТАП ВЫПОЛНЕНИЯ";
            appealProgramDataGrid.Columns[0].Width = 35;
        }

        private void appealProgramView_Click(object sender, RoutedEventArgs e)
        {
            ViewAppealProgramForm viewAppealProgramForm = new ViewAppealProgramForm();
            


            appealProgram? path = appealProgramDataGrid.SelectedItem as appealProgram;
            viewAppealProgramForm.idAppeal.Text = Convert.ToString(path.idAppeal);
            viewAppealProgramForm.nameProgram.Text = Convert.ToString(path.idProgram);
            viewAppealProgramForm.ipPc.Text = Convert.ToString(path.ipPc);
            viewAppealProgramForm.namePc.Text = Convert.ToString(path.pcName);
            viewAppealProgramForm.applicantProgram.Text = Convert.ToString(path.applicant);         
            viewAppealProgramForm.executorProgram.Text = Convert.ToString(path.otpExecutor);

            switch (path.oibStatusResponsible){


                case "Не согласовано": viewAppealProgramForm.oibStatusResponsble.SelectedIndex = 0; break;
                case "Согласовано": viewAppealProgramForm.oibStatusResponsble.SelectedIndex = 1; break;
                case "Отказано": viewAppealProgramForm.oibStatusResponsble.SelectedIndex = 2; break;

            }
            switch (path.oitStatusResponsible)
            {


                case "Не согласовано": viewAppealProgramForm.oitStatusResponsble.SelectedIndex = 0; break;
                case "Согласовано": viewAppealProgramForm.oitStatusResponsble.SelectedIndex = 1; break;
                case "Отказано": viewAppealProgramForm.oitStatusResponsble.SelectedIndex = 2; break;

            }
            if (path.otpExecutor != "Нет исполнителя") viewAppealProgramForm.executorProgram.Text = path.otpExecutor;







            viewAppealProgramForm.ShowDialog();


        }
    }
}
