using Npgsql;
using SupportCenter.Classes;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace SupportCenter
{
    /// <summary>
    /// Логика взаимодействия для AppealForm.xaml
    /// </summary>
    public partial class AppealForm : Window
    {
        public AppealForm()
        {
            InitializeComponent();
        }

        private void cancelButton_Click(object sender, RoutedEventArgs e)
        {
            MainWindow mainWindow = new MainWindow();
            mainWindow.Show();  
            this.Close();
        }

        private void buttonProgram_Click(object sender, RoutedEventArgs e)
        {
            workAreaControl.SelectedIndex = 0;
        }

        private void buttonFolder_Click(object sender, RoutedEventArgs e)
        {
            workAreaControl.SelectedIndex = 1;
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            CreateAppealProgramForm createAppealProgramForm = new CreateAppealProgramForm();
            createAppealProgramForm.ShowDialog();
        }
        public void loadAppealProgram()
        {

            dbConnect db_connect = new dbConnect();
            DataTable table = new DataTable();
            NpgsqlCommand command = new NpgsqlCommand(
                        "SELECT u.id_appeal_program, " +
                        "p.name_program, " +
                        "u.pc_name, " +
                        "u.ip_pc, " +
                        "oib_user.user_name AS oib_user_name, " +
                        "u.oib_status_responsible, " +
                        "oit_user.user_name AS oit_user_name, " +
                        "u.oit_status_responsible, " +
                        "otp_user.user_name AS otp_user_name, " +
                        "u.otp_status_executor " +
                        "FROM main.appealprogram u " +
                        "LEFT JOIN main.users oib_user ON u.oib_responsible = oib_user.user_id " +
                        "LEFT JOIN main.users oit_user ON u.oit_responsible = oit_user.user_id " +
                        "LEFT JOIN main.users otp_user ON u.otp_executor = otp_user.user_id " +
                        "LEFT JOIN main.program p ON u.id_program = p.id_program",
            db_connect.GetConnection());
            db_connect.openConnection();
            command.ExecuteNonQuery();
            NpgsqlDataAdapter adapter = new NpgsqlDataAdapter(command);
            NpgsqlDataReader reader = command.ExecuteReader();
            List<appealProgram> result = new List<appealProgram>();

            while (reader.Read())
            {
                string oibStatus = null;
                string oitStatus = null;
                string otpStatus = null;

                if (Convert.ToString(reader[5]) == "0")
                {
                    oibStatus = " Не согласовано";
                }
                if (Convert.ToString(reader[7]) == "0")
                {
                    oitStatus = "Не согласовано";
                }
                if (Convert.ToString(reader[9]) == "0")
                {
                    otpStatus = "Не в работе";
                }


                result.Add(new appealProgram(Convert.ToInt32(reader[0]), Convert.ToString(reader[1]), Convert.ToString(reader[2]), Convert.ToString(reader[3]), 
                    Convert.ToString(reader[4]), oibStatus, Convert.ToString(reader[6]), oibStatus, Convert.ToString(reader[8]), oibStatus));

            }
            reader.Close();
            appealProgramDataGrid.ItemsSource = result;

           

        }

        private void appealProgramCreate_Click(object sender, RoutedEventArgs e)
        {

        }

        private void appealProgramShow_Click(object sender, RoutedEventArgs e)
        {
            loadAppealProgram();
        }

        private void appealProgramDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            appealProgramDataGrid.Columns[0].Header = "ID";
            appealProgramDataGrid.Columns[1].Header = "ПРОГРАММА";
            appealProgramDataGrid.Columns[2].Header = "КОМПЬЮТЕР";
            appealProgramDataGrid.Columns[3].Header = "IP АДРЕС";
            appealProgramDataGrid.Columns[4].Header = "СОГЛАСУБЮЩИЙ ОИБ";
            appealProgramDataGrid.Columns[5].Header = "СТАТУС";
            appealProgramDataGrid.Columns[6].Header = "СОГЛАСУЮЩИЙ ОИТ";
            appealProgramDataGrid.Columns[7].Header = "СТАТУС";
            appealProgramDataGrid.Columns[8].Header = "ИСПОЛНИТЕЛЬ ОТП";
            appealProgramDataGrid.Columns[9].Header = "ЭТАП ВЫПОЛНЕНИЯ";
            appealProgramDataGrid.Columns[0].Width = 35;
        }
    }
}
