using Npgsql;
using NpgsqlTypes;
using SupportCenter.Api;
using SupportCenter.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace SupportCenter
{
    /// <summary>
    /// Логика взаимодействия для CreateAppealProgramForm.xaml
    /// </summary>
    public partial class CreateAppealProgramForm : Window
    {
        public CreateAppealProgramForm()
        {
            InitializeComponent();
        }

        private void createAppealProgram_Click(object sender, RoutedEventArgs e)
        {
            if (string.IsNullOrEmpty(programAppeal.Text)) MessageBox.Show("Программа не выбрана.");
            else if (string.IsNullOrEmpty(commentAppeal.Text)) MessageBox.Show("Комментарий не указан.");

            else
            {







                RedactUserForm redactForm = new RedactUserForm();
                ProgramDto? path = programDataGrid.SelectedItem as ProgramDto;

                dbConnect db_connect = new dbConnect();
                db_connect.openConnection();
                NpgsqlDataAdapter adapter = new NpgsqlDataAdapter();
                NpgsqlCommand command = new NpgsqlCommand("" +
                    "INSERT INTO main.appealprogram " +
                    "(id_program,pc_name,ip_pc,oib_responsible,oib_status_responsible,oit_responsible,oit_status_responsible,otp_executor,otp_status_executor,applicant,comment) " +
                    "VALUES (@idProgram,@pcName,@ipPc,12,0,11,0,0,0,(select user_id from main.users where login_user=@applicantLogin),@comment)", db_connect.GetConnection());
                command.Parameters.Add("@idProgram", NpgsqlDbType.Integer).Value = path.id_program;
                command.Parameters.Add("@pcName", NpgsqlDbType.Text).Value = Session.CurrentPcName;
                command.Parameters.Add("@ipPc", NpgsqlDbType.Text).Value = Session.CurrentIp;
                command.Parameters.Add("@applicantLogin", NpgsqlDbType.Text).Value = Session.CurrentUserLogin;
                command.Parameters.Add("@comment", NpgsqlDbType.Text).Value = commentAppeal.Text;


                adapter.SelectCommand = command;
                command.ExecuteReader();
                db_connect.closeConnection();
                MessageBox.Show("Обращение создано.");
                this.Close();

            }
        }

        private async void selectProgram_Click(object sender, RoutedEventArgs e)
        {
            Application.Current.MainWindow = this;
            Application.Current.MainWindow.Width = 850;

            try
            {
                var api = new ProgramApiGet();
                var program = await api.GetProgramAsync();

                programDataGrid.ItemsSource = program;

            }
            catch (Exception ex)
            {
                MessageBox.Show("Ошибка при получении данных: " + ex.Message);
            }


            programDataGrid.Columns[0].Width = new DataGridLength(1, DataGridLengthUnitType.Star);


        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            Application.Current.MainWindow = this;
            Application.Current.MainWindow.Width = 550;
        }

        private void selectProgramDg_Click(object sender, RoutedEventArgs e)
        {
            Application.Current.MainWindow = this;
            Application.Current.MainWindow.Width = 550;
           
            ProgramDto? path = programDataGrid.SelectedItem as ProgramDto;
            programAppeal.Text = path.name_program;
            if (path != null)
            {

                programAppeal.Text = path.name_program;


            }
            else
            {

                MessageBox.Show("Программа не выбрана");

            }

        }

        private void programDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            programDataGrid.Columns[0].Header = "НАИМЕНОВАНИЕ ПРОГРАММЫ";
        }

        private async void selectFolder_Click(object sender, RoutedEventArgs e)
        {
            Application.Current.MainWindow = this;
            Application.Current.MainWindow.Width = 850;

            try
            {
                var api = new FolderApiGet();
                var program = await api.GetFolderAsync();

                programDataGrid.ItemsSource = program;

            }
            catch (Exception ex)
            {
                MessageBox.Show("Ошибка при получении данных: " + ex.Message);
            }


            programDataGrid.Columns[0].Width = new DataGridLength(1, DataGridLengthUnitType.Star);
        }
    }
}
